version: "3"

services:
  api:
    container_name: api
    build: .
    command: npm run dev
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app/
    depends_on:
      - database
    networks:
      - app-network
  database:
    image: postgres
    environment:
      - POSTGRES_DB=apidb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - ./database/:/data/postgres
    networks:
      - app-network



networks:
  app-network:
    driver: bridge